name: CICD

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Instal dependensies
        run: npm install

      - name: Tests
        run: echo "no tests" #npm run test

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mdsdimat/node-prakt:latest
          
      - name: Fetch docker image to server and run
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} -i ${{ secrets.SSH_PRIVATE_KEY }} "cd /var/www/html && docker pull mdsdimat/node-prakt && docker stop html_app_1 && docker run html_app_1" 
