name: CICD

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    env:
      sshkey: ${{ secrets.SSH_PRIVATE_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with: 
          node-version: 12
     # - name: Instal dependensies
     #   run: npm install

      - name: Tests
        run: echo "no tests" #npm run test

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1 
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      
      #- name: Build and push
      #  id: docker_build
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: mdsdimat/node-prakt:latest
      - name: Create known hosts
        run: |
          mkdir -p ~/.Ssh/
          echo "$DO_GITHUB_PRIVATE_KEY" > ../github_do.key
          sudo chmod 600 ../github_do.key
          ssh-keyscan -H ${{secrets.DEPLOY_SERVER}} > ~/.Ssh/known_hosts
        shell: bash

      #- name: Fetch docker image to server and run
      - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} -i ~/.Ssh/known_hosts.txt "cd /var/www/html && docker pull mdsdimat/node-prakt && docker stop html_app_1 && docker run html_app_1" 
